# Numpy and Python Basics

Hello Everyone! My Name is Erika Peláez and I'm going to talk a little bit about Python, Numpy and why it was important to the Pytorch Challenge.

### In the beginning there was only Python...

<center><img src='pyastro_logo.svg' width=180></center>

As you might already know, Python is a high-level programming language that has gain a lot of followers in the scientific and data science comunity due to the faily simple syntax, all of the batteries that includes and the third part libraries that we all use and love. One of this famous and ubiquitous libraries is **Numpy**.

There is a lot of resources for learning Python and there's actually [courses from udacity](https://www.udacity.com/course/introduction-to-python--ud1110) that can help you get your Python to the next level. If you already know how to program and are familiar with the object oriented paradigm you could actually just check out the site [learn x in y minutes](https://learnxinyminutes.com/docs/python3/) where x is python 3.x so you can basically see what the syntax is about.

For the purposes of this course you will also have to be familiar with libraries such as numpy, however the level that you have to have with numpy is not of an expert user, if we just go over some of the basic operations and concepts from numpy we can successfully complete lesson 2 of the challenge

### What is Numpy about?

In a nutshell, numpy is a library that offers the ability to compute over arrays and matrices. It also happens to have implementations of mathematical functions commonly used in scientific computing. Lets begin by importing Numpy.

In [1]:
#Let's import numpy
#Because we're too lazy to write numpy everytime we'll give it an alias "np"

import numpy as np

Now that we have numpy imported we can start playing with "vectors and matrices". We will use this terms from now on to remind us that we are going to perform linear algebra operations altough we have to keep in mind that they are strictly arrays with different *ranks*.

Let's first create some vectors

In [12]:
#from a python list
vector_list = np.array([1, 2, 3])
#an all zero array
vector_zero = np.zeros(3)
#an all ones array
vector_ones = np.ones(3)
#from a range of numbers from 0 to 9 with step 2
vector_range = np.arange(0,9,2)

Let's examine the properties of our vectors

In [18]:
#Get the dimensions of the vector in this case is 3
print(vector_list.shape)
#Get the size of the vector, how many elements there are
print(vector_list.size)
#Whats the type of object it contains
print(vector_list.dtype)

(3,)
3
int64


You can check the properties of the rest of the created vectors as an exercise

Now let's add more dimensions to it. We are going to create a matrix with the three first  vectors

In [21]:
matrix = np.array([vector_ones, vector_list, vector_zero])
print(matrix)

[[1. 1. 1.]
 [1. 2. 3.]
 [0. 0. 0.]]


Do you notice anything different? Perhaps we should checkout the types in the array to find out

In [23]:
print(vector_list.dtype)
print(matrix.dtype)

int64
float64


As you can see the type of the vector was cast as float as a consequence of being bundled up togheter with the other float type vectors. This happens because every numpy array **has** to have the same data types within itself.

### Basic operations with numpy

All the arithmetic operations in numpy are performed *element wise* and the result of that is contained in a new array.

#### Operations between two vectors

In [24]:
vector_list + vector_ones

array([2., 3., 4.])

In [26]:
vector_zero - vector_ones

array([-1., -1., -1.])

#### Operations with one scalar and one vector

In [33]:
vector_zero + 3

array([3., 3., 3.])

In [34]:
vector_list/(vector_zero + 2)

array([0.5, 1. , 1.5])

Now see what happens when the shapes of two vectos don't match

In [27]:
#What happens if we have different dimensions in the two vectors (ValueError)
vector_list * vector_range

ValueError: operands could not be broadcast together with shapes (3,) (5,) 

#### Operations between matrices and vectors

In [40]:
print(f'vector from list:\n{vector_list}')
print(f'matrix:\n{matrix}')
print(f'product:\n{vector_list*matrix}')

vector from list:
[1 2 3]
matrix:
[[1. 1. 1.]
 [1. 2. 3.]
 [0. 0. 0.]]
product:
[[1. 2. 3.]
 [1. 4. 9.]
 [0. 0. 0.]]


Do you notice something off with this? Normally in linear algebra whenever we multiply a vector and a matrix we get a vector as a result like so:

<center><img src='https://keisan.casio.com/has10/mimetex.cgi?%5Chspace{30}Ax=c%5C%5C%5Cvspace{5}%3Cbr%20/%3E%5Cnormal{%5Cleft[%5Cbegin{array}%5Cvspace{10}%20a_{%5Csmall%2011}&%20%5Ccdots&%20a_{%5Csmall%201j}%5C%5C%5Cvspace{10}%20a_{%5Csmall%2021}&%20%5Ccdots&%20a_{%5Csmall%202j}%5Cvspace{20}%5C%5C%20%5Cvdots&%20%5Cddots&%20%5Cvdots%5Cvspace{10}%5C%5Ca_{%5Csmall%20i1}&%20%5Ccdots&%20a_{%5Csmall%20ij}%5C%5C%5Cend{array}%5Cright]}%20%3Cbr%20/%3E%5Cnormal{%5Cleft(%5Cbegin{array}%5Cvspace{10}%20x_1%5C%5C%5Cvspace{10}%20x_2%5Cvspace{20}%5C%5C%5Cvdots%5C%5Cx_j%5C%5C%5Cend{array}%5Cright)}%3Cbr%20/%3E=%5Cnormal{%5Cleft(%5Cbegin{array}%5Cvspace{10}%20%5Csum%20a_{1j}x_j%5C%5C%5Cvspace{10}%20%5Csum%20a_{2j}x_j%5Cvspace{20}%5C%5C%5Cvdots%5C%5C%5Csum%20a_{ij}x_j%5C%5C%5Cend{array}%5Cright)}%5C%5C%3Cbr%20/%3E'></center>

In this case numpy is calculating the Hadamard product which follows the *element wise* phylosophy of numpy.

If you can't remember your linear algebra classes and you want to quickly brush up you can find a "cheat sheet" of linear algebra for Deep Learning [here](https://towardsdatascience.com/linear-algebra-cheat-sheet-for-deep-learning-cd67aba4526c)

If you want to achieve the "dot" product you should use any of the options below. 

In [29]:
np.matmul(vector_list, vector_ones)

6.0

In [30]:
np.dot(vector_list, vector_ones)

6.0

In [32]:
(vector_list * vector_ones).sum()

6.0

In [41]:
np.dot(vector_list, matrix)

array([3., 5., 7.])

In [42]:
np.matmul(vector_list, matrix)

array([3., 5., 7.])

In [44]:
vector_list @ matrix

array([3., 5., 7.])

That makes you wonder what are the differences between every method. Well `np.dot` is mostly used to calculate the dot product of vectors and can be used for scalar multiplication but it is discouraged. `np.matmul` is mainly to get the inner product of matrices and does not allow multiplication by scalars. According to the numpy documentation `np.matmul` differs from `np.dot` in two important ways.

>Multiplication by scalars is not allowed.
>
>Stacks of matrices are broadcast together as if the matrices were elements.

The `(vector_list * vector_ones).sum()` way to do it is just following the formula in the image but is recomended to use the `np.dot` function instead and the `@` operator is like `np.matmul`. 

If you want to now more about that you can read the documentation for [dot](https://docs.scipy.org/doc/numpy/reference/generated/numpy.dot.html#numpy.dot) and [matmul](https://docs.scipy.org/doc/numpy/reference/generated/numpy.matmul.html#numpy.matmul)


#### Operations between matrices

In [48]:
#Matrix of 9 elements (3x3) filled with ones
matrix_ones = np.ones((3, 3))
print(matrix_ones)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [50]:
#Matrix created with numbers from 0 to 9 reshaped to have 3 rows by 3 columns
matrix_range = np.arange(9).reshape((3, 3))
print(matrix_range)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [56]:
#matrix of 9 random numbers with a mean of 0 and a Standard deviation of 0.1
matrix_random = np.random.normal(0, 0.1, 9).reshape(3, 3)
print(matrix_random)

[[ 0.07431159 -0.06486389  0.02790005]
 [ 0.03262619  0.15215935 -0.07532998]
 [-0.17847398  0.04601822  0.21418014]]


In [57]:
matrix_ones + matrix_range

array([[1., 2., 3.],
       [4., 5., 6.],
       [7., 8., 9.]])

In [58]:
matrix_random * matrix_range

array([[ 0.        , -0.06486389,  0.05580011],
       [ 0.09787858,  0.60863742, -0.3766499 ],
       [-1.07084388,  0.32212757,  1.7134411 ]])

In [59]:
matrix_random @ matrix_range

array([[-0.02719136,  0.0101564 ,  0.04750415],
       [ 0.00449818,  0.11395375,  0.22340931],
       [ 1.4231355 ,  1.50485988,  1.58658426]])

In [60]:
#transposing a matrix
matrix_range.T

array([[0, 3, 6],
       [1, 4, 7],
       [2, 5, 8]])

#### Numpy mathematical functions

The options you have to operate in the arrays are quite comprehensive. If you take a look at the list [here](https://docs.scipy.org/doc/numpy/reference/routines.math.html) you will realize how vast the functions are (but if you want to go more general [here](https://docs.scipy.org/doc/numpy/reference/routines.html) are all the functions in numpy). In this challenge we basically make use of two famous functions the `np.exp` and the `np.log` to calculate the exponetial and natural logarithmic functions of each element in our array


In [62]:
exp = np.exp(vector_list)
print(exp)

[ 2.71828183  7.3890561  20.08553692]


In [63]:
np.log(exp)

array([1., 2., 3.])

### Tips, tricks and final remarks

And that is as simple as that! This is all you need to successfully complete lesson 2 in the challenge! and is also a good way to understand some of the functions in pytorch that you will be using in further lessons

If you are using jupyter, colab or ipython it is useful to note that it provides the handy-dandy "autocomplete". So if you forget what methods you have access to in numpy just type `np.`and then press the "tab" key to see what are the options that you have. You can as for help in the form of docstrings as well, the only thing you have to do is type `np.exp?` and follow by enter to access the documentation.

Finally, *Don't panic* this might be a little overwhelming for some people but **everything** can be mastered with practice.

I hope everyone to have an enriching experience during this course and that we all end up being experts in Deep Learning!

P.S If you have a suggestion or I made a mistake or typo somewhere here I encourage you to make 